{
 "title": "Hive / Adservice Sentinel",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_Concurrency",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_Rt",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exception-qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_ExceptionQps",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "block-qps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_BlockQps",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "success-qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_SuccessQps",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pass-qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_PassQps",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "occupied-pass-qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_OccupiedPassQps",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "classification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_Classification",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "timestamp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_Timestamp",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_Version",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}