{
 "title": "Hive / 应用治理监控",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "并发",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_Concurrency",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_Rt",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "阻塞QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_BlockQps",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "异常QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_ExceptionQps",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "通过QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_PassQps",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "成功QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "Sentinel_adservice-springcloud_PassQps",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}